### ISSUE TITLE
API call in sandbox mode gives "Access denied. Access key is not valid"

### ISSUE THREAD

**Issue by StefanNeuser** [netresearch/dhl-sdk-api-location-finder#1]
Hi, good work :-) When call the api with sandbox credentials i'm getting "Access denied. Access key is not valid." all the time. Is this service only for dhl prod api available?

**Comment by ngolatka** [comment]
Hello @StefanNeuser , my first thought would be checking if you used the correct credentials. Obviously, you can't (or shouldn't) post them here. Can you please send them via [this contact form](https://dhl.support.netresearch.de/support/tickets/new)? That will end up on my desk and I can check what's wrong.

**Comment by mam08ixo** [comment]
I just tested sandbox access and can confirm it still works.
Make sure you have an application token created in [Developer Portal](https://entwickler.dhl.de/group/ep/myapps) that is authorized to access the desired resources.

![myapps__token](https://user-images.githubusercontent.com/1771622/88401773-73510980-cdca-11ea-8ee2-a64544aca22b.png)

**Comment by StefanNeuser** [comment]
Yes, did the trick. Sorry that i did not respond here and many thanks for your answer. I checked you package, its really well coded but overengineer for my usecase. i did it this way:

```
    $auth_params = array(
        'login'    => config('dhl.username'),
        'password' => config('dhl.password'),
        'location' => config('dhl.url'),
        'trace'    => 1
    );

    $client = new SoapClient("https://cig.dhl.de/cig-wsdls/com/dpdhl/wsdl/standortsuche-api/1.1/standortsuche-api-1.1.wsdl", $auth_params);

    $data = [
        'key' => '',
        'address' => [
            "street" => $request->input('street', ''),
            "streetNo" => $request->input('streetNo', ''),
            "zip" => $request->input('zip', ''),
            "city" => $request->input('city', ''),
            "countryCode" => "DE"
        ]
    ];

    try
    {
        $response = $client->getPackstationsByAddress($data);
    }
    catch (\Exception $e)
    {
        return $e->getMessage();
    }

    if (is_soap_fault($response) || (isset($response->status) && $response->status->StatusCode != 0))
    {
        if (is_soap_fault($response))
        {
            return $response->faultstring;
        }
        else
        {
            return $response->status->StatusMessage;
        }
    }

    return json_decode(json_encode($response), true)['packstation'];

    // kann man machen wenn nötig
    return collect($response->packstation)->map(function ($p)
    {
        return [
            'id' => $p->id,
            'objectId' => $p->objectId,
            'packstationId' => $p->packstationId,
        ];
    });
```
